# Copyright ©2021. Element 84, Inc. All Rights Reserved.
version:                "3"
services:
  geonotebook:
      build: .
      image: matthewhanson/geo-notebook 
      env_file: .env
      volumes:
        - ./:/home/jovyan/work
      ports:
        - 18888:18888
      entrypoint: |
        jupyter notebook --notebook-dir=work/notebooks --no-browser --ip=0.0.0.0 --port=18888
