name: odc
channels:
  - conda-forge
dependencies:
  # Pin these as current cartopy struggles with shapely 1.8+
  - python=3.9
  - cartopy
  - shapely
  - geopandas
  - datacube
  - pystac
  - pystac-client
  - odc-stac
  - coiled
  - stackstac
  - rasterio
  - rioxarray
  - planetary-computer
  - dask-image
  - dask-labextension
  - hvplot
  - ipykernel
  - geoviews
  - datashader
  - jupyter-server-proxy
  - pip
  - pip:
      - geogif
      - odc-algo
