name: odc
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - cartopy
  - shapely
  - geopandas
  - geogif
  - datacube
  - pystac
  - pystac-client
  - odc-stac >= 0.3.1
  - coiled
  - stackstac
  - rasterio
  - rioxarray
  - planetary-computer
  - dask-image
  - dask-labextension
  - hvplot
  - geoviews
  - datashader
  - jupyter-server-proxy
